### ISSUE TITLE
compresor

### ISSUE THREAD

**Issue by amircloner** [ilteoood/tele_uploader#5]
hi Matteo 

when run : install composer 
two error show
1.

  [RuntimeException]
  Failed to clone https://github.com/danog/phpseclib via https, ssh protocols
  , aborting.

  - https://github.com/danog/phpseclib
    Cloning into '/home/streamb2/public_html/up/vendor/phpseclib/phpseclib'..
  .
    done.
    fatal: unable to create thread: Resource temporarily unavailable
    fatal: cannot repack to clean up

  - git@github.com:danog/phpseclib
    Cloning into '/home/streamb2/public_html/up/vendor/phpseclib/phpseclib'..
  .
    done.
    fatal: unable to create thread: Resource temporarily unavailable
    fatal: cannot repack to clean up

2.

Failed to download rollbar/rollbar from source: Failed to clone https://github.com/rollbar/rollbar-php.git via https, ssh protocols, aborting.

- https://github.com/rollbar/rollbar-php.git
  Cloning into '/home/streamb2/public_html/up/vendor/rollbar/rollbar'...
  done.
  fatal: unable to create thread: Resource temporarily unavailable
  fatal: cannot repack to clean up

- git@github.com:rollbar/rollbar-php.git
  Cloning into '/home/streamb2/public_html/up/vendor/rollbar/rollbar'...
  done.
  fatal: unable to create thread: Resource temporarily unavailable
  fatal: cannot repack to clean up

    Now trying to download from dist

and  dont creat  " autolouder.php"

**Comment by ilteoood** [comment]
Hi,
which version of PHP and composer are you using?
I've tried to install everything using this Dockerfile:

`
FROM composer:latest
WORKDIR tele_uploader
ADD . .
RUN ["composer", "install"]
`

and everything work. I think that there is a problem on your machine.

**Comment by amircloner** [comment]
hi 
Thank you very much for helping me

php 7.2

and i work on cpanel
how i install it in docker?

**Comment by amircloner** [comment]
this project have a docker file?

**Comment by ilteoood** [comment]
Hi,
the docker file that I've attached above is just a test to prove that the "composer install" command works.

Btw, I think that this is a problem with composer; take a look here:
https://github.com/composer/composer/issues/2176

And, if necessary, update your composer version to (at least) 1.6.3.

**Comment by amircloner** [comment]
bot id in enb.sh with @ or not?

**Comment by amircloner** [comment]
i found out https://github.com/danog/phpseclib problem in the cpanel i/o was limited and composer packages is very heavy  ;result is dont continue download packages 

my composer version 1.7.2

any way to first locate the packages in vendor and begin  run    composer install?

**Comment by ilteoood** [comment]
You could try to download the vendor packages on your pc and then upload them to the remote host.
Isn't the best solution, at this point I suggest to abandon cPanel

**Comment by amircloner** [comment]
Finally its run 
Thank you very much for helping me

I'll be happy you add the project google dive save
