### ISSUE TITLE
 your PHP version does not satisfy that requirement.

### ISSUE THREAD

**Issue by tomasmetal23** [ilteoood/tele_uploader#7]
From php 5.6 it gives me this problem when running $ composer install

Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for amphp/dns dev-master -> satisfiable by amphp/dns[dev-master].
    - amphp/dns dev-master requires php >=7.0 -> your PHP version (5.6.33) does not satisfy that requirement.
  Problem 2
    - Installation request for amphp/file dev-master -> satisfiable by amphp/file[dev-master].
    - amphp/file dev-master requires php >=7.1 -> your PHP version (5.6.33) does not satisfy that requirement.
  Problem 3
    - Installation request for rollbar/rollbar dev-master -> satisfiable by rollbar/rollbar[dev-master].
    - rollbar/rollbar dev-master requires php >=8.0.0 <9.0 -> your PHP version (5.6.33) does not satisfy that requirement.
  Problem 4
    - danog/madelineproto 3.1 requires rollbar/rollbar dev-master -> satisfiable by rollbar/rollbar[dev-master].
    - danog/madelineproto 3.1.1 requires rollbar/rollbar dev-master -> satisfiable by rollbar/rollbar[dev-master].
    - rollbar/rollbar dev-master requires php >=8.0.0 <9.0 -> your PHP version (5.6.33) does not satisfy that requirement.
    - Installation request for danog/madelineproto ^3.1 -> satisfiable by danog/madelineproto[3.1, 3.1.1].

**Comment by ilteoood** [comment]
It is not maintained anymore.
